"""Initial tables

Revision ID: 34cae3f68dbd
Revises: d37ad456df92
Create Date: 2025-12-15 14:48:58.097971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cae3f68dbd'
down_revision: Union[str, Sequence[str], None] = 'd37ad456df92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('poll_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['poll_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'poll_id')
    # ### end Alembic commands ###
